# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('counseling', 'Counseling appointment'), ('home_visit', 'Home visit'), ('hospital_visit', 'Hospital visit'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.TextField(help_text="What you'd like the pastoral team to know.")),
                ('preferred_contact_method', models.CharField(blank=True, help_text="e.g. 'Call my cell', 'Text is best' - optional.", max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='When a visit or appointment is scheduled for.', null=True)),
                ('pastor_notes', models.TextField(blank=True, help_text='Private notes, visible only to Pastors.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_pastor', models.ForeignKey(blank=True, help_text='Which pastor is handling this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_requests', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
