# Generated by Django 5.2.17 on 2026-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Sunday Service - June 1, 2027"', max_length=200)),
                ('stream_url', models.URLField(help_text='Link to the YouTube/Facebook live stream or recording.')),
                ('scheduled_for', models.DateTimeField(help_text='When this service is/was streamed.')),
                ('notes', models.TextField(blank=True, help_text='Optional - e.g. the sermon topic or a special note.')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
