# Generated by Django 5.2.17 on 2026-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='featured_on_homepage',
            field=models.BooleanField(default=False, help_text='Show this one on the homepage right now. Only one stream should be featured at a time - turning this on for one automatically turns it off for every other stream.'),
        ),
    ]
