# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an MP3 to include this sermon in the podcast feed (/sermons/podcast.xml).', null=True, upload_to='sermon_audio/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='study_guide',
            field=models.FileField(blank=True, help_text="Optional PDF study guide/notes sheet, downloadable from this sermon's public page.", null=True, upload_to='sermon_study_guides/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Optional - part of a multi-week teaching series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermonseries'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sermons', to='sermons.tag'),
        ),
    ]
