# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
        ('sermons', '0002_sermonseries_tag_sermon_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='discussion_guide',
            field=models.FileField(blank=True, help_text='Optional small-group discussion guide (questions tied to this message) for group leaders.', null=True, upload_to='sermon_discussion_guides/'),
        ),
        migrations.CreateModel(
            name='SermonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_progress', to='members.member')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_progress', to='sermons.sermon')),
            ],
            options={
                'verbose_name_plural': 'Sermon progress',
                'unique_together': {('member', 'sermon')},
            },
        ),
    ]
