# Generated by Django 5.2.17 on 2026-09-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='members.member'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_signups', to='members.member'),
        ),
        migrations.AddField(
            model_name='volunteerslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_slots', to='events.event'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='events.volunteerslot'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('event', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='volunteersignup',
            unique_together={('slot', 'member')},
        ),
    ]
