# Generated by Django 5.2.17 on 2026-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, help_text='Reference/transaction ID from the payment provider.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EventServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. '8:00 AM Service' or 'Main Sanctuary'.", max_length=100)),
                ('start_time', models.TimeField(blank=True, help_text='What time this specific service starts.', null=True)),
                ('location', models.CharField(blank=True, help_text="Overrides the event's own location, if this service meets somewhere else.", max_length=200)),
            ],
            options={
                'ordering': ['start_time', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Adult", "Child", "Early bird"', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for no limit.', null=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
