# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_eventservicetime_eventticket'),
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Which campus this event is at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='members.campus'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', help_text='Generates future occurrences when this event is first created. Has no effect when editing an existing event.', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='series_parent',
            field=models.ForeignKey(blank=True, help_text='Set automatically on events generated from a recurring series.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='members.member'),
        ),
        migrations.AddField(
            model_name='eventservicetime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_times', to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='service_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='events.eventservicetime'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.eventticket'),
        ),
    ]
