# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_campus_event_recurrence_event_series_parent_and_more'),
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_waitlist_entries', to='members.member')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.volunteerslot')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('slot', 'member')},
            },
        ),
    ]
