# Generated by Django 5.2.17 on 2026-09-28 00:47

import events.models
from django.db import migrations, models
from datetime import timedelta


def backfill_reservations(apps, schema_editor):
    Registration = apps.get_model('events', 'EventRegistration')
    for registration in Registration.objects.using(schema_editor.connection.alias).select_related('ticket').iterator():
        registration.amount_due = registration.ticket.price
        registration.expires_at = registration.registered_at + timedelta(minutes=30)
        registration.save(using=schema_editor.connection.alias, update_fields=['amount_due', 'expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_volunteerwaitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checkout_url',
            field=models.URLField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='expires_at',
            field=models.DateTimeField(default=events.models.reservation_deadline),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('review', 'Paid - staff review required')], default='pending', max_length=10),
        ),
        migrations.RunPython(backfill_reservations, migrations.RunPython.noop),
    ]
