# Generated by Django 5.2.17 on 2026-09-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('pledge', 'Pledge'), ('other', 'Other')], default='offering', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Reference/transaction ID from the payment provider.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
