# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0001_initial'),
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Which campus this gift was given at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.campus'),
        ),
        migrations.CreateModel(
            name='GivingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional target amount. Leave blank for a campaign with no fixed goal.', max_digits=12, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive campaigns are hidden from the public giving page and the pledge/give forms.')),
                ('sms_keyword', models.CharField(blank=True, default='', help_text='Optional word for text giving, e.g. "BUILDING" - a member texts "GIVE 100 BUILDING" to tag a gift to this campaign.', max_length=20)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this campaign is for (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_campaigns', to='members.campus')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Which giving campaign this gift counts toward, if any (only relevant while a campaign is running).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='giving.givingcampaign'),
        ),
        migrations.CreateModel(
            name='RecurringGiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('next_due_date', models.DateField(help_text='The next date a reminder to give goes out.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Optional - leave blank for a recurring gift to the general fund rather than a specific campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_gifts', to='giving.givingcampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_gifts', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_pledged', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='giving.givingcampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.member')),
            ],
            options={
                'ordering': ['-date_pledged'],
                'unique_together': {('campaign', 'member')},
            },
        ),
    ]
