# Generated by Django 5.2.17 on 2026-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0002_donation_campus_givingcampaign_donation_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringgiving',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
