# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('submitted_date', models.DateField(blank=True, help_text='When the check was requested/submitted.', null=True)),
                ('cleared_date', models.DateField(blank=True, help_text='When the check came back cleared.', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='When this clearance needs to be renewed.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
