# Generated by Django 5.2.17 on 2026-09-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(help_text='e.g. "Child Safety", "First Aid", "Safe Sanctuary".', max_length=150)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('completed_date', models.DateField(blank=True, help_text='When this training was completed.', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='When this training needs to be renewed, if it expires at all.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
