# Generated by Django 5.2.17 on 2026-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Shown as the image's alt text and as a caption under it on the homepage.", max_length=150)),
                ('image', models.ImageField(upload_to='flyers/')),
                ('link_url', models.URLField(blank=True, help_text='Optional - where the flyer links to, e.g. an event page or giving campaign.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active flyers show on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
