# Generated by Django 5.2.17 on 2026-10-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_staffloginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Optional planned spend for the year. Leave blank to track spend with no budget comparison.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Budget categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(blank=True, help_text="Vendor/person paid, e.g. 'ECG', 'ABC Plumbing'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, help_text='A photo or scan of the receipt, if you have one.', null=True, upload_to='expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this expense is for (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='members.campus')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.budgetcategory')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
