# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Which campus this item belongs to (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='members.campus'),
        ),
        migrations.AddField(
            model_name='equipmentcheckout',
            name='checked_out_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='equipmentcheckout',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='equipment.equipment'),
        ),
    ]
