from django.urls import path

from . import views

urlpatterns = [
    path("", views.staff_home, name="staff_home"),
    path("search/", views.staff_search, name="staff_search"),
    path("members/", views.member_list, name="staff_member_list"),
    path("members/new/", views.member_create, name="staff_member_create"),
    path("members/import/", views.member_import, name="staff_member_import"),
    path("members/export/", views.member_export, name="staff_member_export"),
    path("backup/", views.full_backup_export, name="staff_full_backup"),
    path("directory-booklet/", views.directory_booklet, name="staff_directory_booklet"),
    path("activity-log/", views.activity_log, name="staff_activity_log"),
    path("members/<int:member_id>/", views.member_detail, name="staff_member_detail"),
    path("members/<int:member_id>/id-card/", views.member_id_card, name="staff_member_id_card"),
    path("members/<int:member_id>/id-card/qr/", views.member_id_card_qr, name="staff_member_id_card_qr"),
    path(
        "members/<int:member_id>/membership-certificate/",
        views.membership_certificate_pdf,
        name="staff_membership_certificate_pdf",
    ),
    path("members/<int:member_id>/notes/new/", views.member_note_create, name="staff_member_note_create"),
    path("members/<int:member_id>/edit/", views.member_edit, name="staff_member_edit"),
    path(
        "members/<int:member_id>/pathway/<int:step_id>/mark/",
        views.mark_pathway_step,
        name="staff_mark_pathway_step",
    ),
    path("pathway-steps/", views.pathway_step_list, name="staff_pathway_step_list"),
    path("pathway-steps/new/", views.pathway_step_create, name="staff_pathway_step_create"),
    path("pathway-steps/<int:step_id>/edit/", views.pathway_step_edit, name="staff_pathway_step_edit"),
    path("households/", views.household_list, name="staff_household_list"),
    path("households/new/", views.household_create, name="staff_household_create"),
    path("households/<int:household_id>/", views.household_detail, name="staff_household_detail"),
    path("households/<int:household_id>/edit/", views.household_edit, name="staff_household_edit"),
    path("households/<int:household_id>/members/add/", views.household_add_member, name="staff_household_add_member"),
    path(
        "households/<int:household_id>/members/<int:member_id>/remove/",
        views.household_remove_member,
        name="staff_household_remove_member",
    ),
    path("households/<int:household_id>/bulk-action/", views.household_bulk_action, name="staff_household_bulk_action"),
    path("campuses/", views.campus_list, name="staff_campus_list"),
    path("campuses/new/", views.campus_create, name="staff_campus_create"),
    path("campuses/<int:campus_id>/", views.campus_detail, name="staff_campus_detail"),
    path("campuses/<int:campus_id>/edit/", views.campus_edit, name="staff_campus_edit"),
    path("groups/", views.group_list, name="staff_group_list"),
    path("groups/new/", views.group_create, name="staff_group_create"),
    path("groups/<int:group_id>/", views.group_detail, name="staff_group_detail"),
    path("groups/<int:group_id>/edit/", views.group_edit, name="staff_group_edit"),
    path("groups/<int:group_id>/members/add/", views.group_add_member, name="staff_group_add_member"),
    path(
        "groups/<int:group_id>/members/<int:member_id>/remove/",
        views.group_remove_member,
        name="staff_group_remove_member",
    ),
    path("events/", views.event_list, name="staff_event_list"),
    path("events/roster-gaps/", views.roster_gaps, name="staff_roster_gaps"),
    path("events/new/", views.event_create, name="staff_event_create"),
    path("events/<int:event_id>/", views.event_detail, name="staff_event_detail"),
    path("events/<int:event_id>/edit/", views.event_edit, name="staff_event_edit"),
    path("events/<int:event_id>/slots/new/", views.volunteer_slot_create, name="staff_slot_create"),
    path("slots/<int:slot_id>/edit/", views.volunteer_slot_edit, name="staff_slot_edit"),
    path(
        "events/<int:event_id>/service-times/new/",
        views.event_service_time_create,
        name="staff_event_service_time_create",
    ),
    path("events/<int:event_id>/tickets/new/", views.ticket_create, name="staff_ticket_create"),
    path("tickets/<int:ticket_id>/edit/", views.ticket_edit, name="staff_ticket_edit"),
    path("donations/", views.donation_list, name="staff_donation_list"),
    path("donations/new/", views.donation_create, name="staff_donation_create"),
    path("donations/<int:donation_id>/complete/", views.donation_mark_completed, name="staff_donation_complete"),
    path("campaigns/", views.campaign_list_staff, name="staff_campaign_list"),
    path("campaigns/new/", views.campaign_create_staff, name="staff_campaign_create"),
    path("campaigns/<int:campaign_id>/", views.campaign_detail_staff, name="staff_campaign_detail"),
    path("campaigns/<int:campaign_id>/edit/", views.campaign_edit_staff, name="staff_campaign_edit"),
    path(
        "campaigns/<int:campaign_id>/send-reminders/",
        views.campaign_send_reminders,
        name="staff_campaign_send_reminders",
    ),
    path("recurring-giving/", views.recurring_giving_list, name="staff_recurring_giving_list"),
    path(
        "recurring-giving/<int:recurring_id>/deactivate/",
        views.recurring_giving_deactivate,
        name="staff_recurring_giving_deactivate",
    ),
    path("livestream/", views.livestream_list, name="staff_livestream_list"),
    path("livestream/new/", views.livestream_create, name="staff_livestream_create"),
    path("livestream/<int:stream_id>/edit/", views.livestream_edit, name="staff_livestream_edit"),
    path("flyers/", views.flyer_list, name="staff_flyer_list"),
    path("flyers/new/", views.flyer_create, name="staff_flyer_create"),
    path("flyers/<int:flyer_id>/edit/", views.flyer_edit, name="staff_flyer_edit"),
    path("sermons/", views.sermon_list_staff, name="staff_sermon_list"),
    path("sermons/new/", views.sermon_create, name="staff_sermon_create"),
    path("sermons/<int:sermon_id>/edit/", views.sermon_edit, name="staff_sermon_edit"),
    path("sermon-series/", views.series_list_staff, name="staff_series_list"),
    path("sermon-series/new/", views.series_create, name="staff_series_create"),
    path("sermon-series/<int:series_id>/edit/", views.series_edit, name="staff_series_edit"),
    path("devotionals/", views.devotional_list_staff, name="staff_devotional_list"),
    path("devotionals/new/", views.devotional_create, name="staff_devotional_create"),
    path("devotionals/<int:devotional_id>/edit/", views.devotional_edit, name="staff_devotional_edit"),
    path("prayer/", views.prayer_list, name="staff_prayer_list"),
    path("prayer/<int:prayer_request_id>/mark-prayed/", views.prayer_mark_prayed, name="staff_prayer_mark_prayed"),
    path("prayer/<int:prayer_request_id>/assign/", views.prayer_assign, name="staff_prayer_assign"),
    path(
        "prayer/<int:prayer_request_id>/wall-approval/",
        views.prayer_set_wall_approval,
        name="staff_prayer_set_wall_approval",
    ),
    path("suggestions/", views.suggestion_list, name="staff_suggestion_list"),
    path(
        "suggestions/<int:suggestion_id>/mark-reviewed/",
        views.suggestion_mark_reviewed,
        name="staff_suggestion_mark_reviewed",
    ),
    path("testimonies/", views.testimony_list, name="staff_testimony_list"),
    path(
        "testimonies/<int:testimony_id>/approve/",
        views.testimony_approve,
        name="staff_testimony_approve",
    ),
    path("reports/", views.reports_overview, name="staff_reports"),
    path("reports/annual-statistics/", views.annual_statistics_report, name="staff_annual_statistics"),
    path("reports/giving-by-member/", views.giving_by_member_report, name="staff_giving_by_member"),
    path(
        "reports/giving-by-member/<int:member_id>/statement/",
        views.annual_giving_statement,
        name="staff_annual_giving_statement",
    ),
    path("children/", views.child_list, name="staff_child_list"),
    path("children/new/", views.child_create, name="staff_child_create"),
    path("children/<int:child_id>/", views.child_detail, name="staff_child_detail"),
    path("children/<int:child_id>/edit/", views.child_edit, name="staff_child_edit"),
    path("checkins/", views.checkin_dashboard, name="staff_checkin_dashboard"),
    path("checkins/new/", views.checkin_create, name="staff_checkin_create"),
    path("checkins/<int:checkin_id>/confirmation/", views.checkin_confirmation, name="staff_checkin_confirmation"),
    path("checkins/<int:checkin_id>/badge/", views.checkin_badge, name="staff_checkin_badge"),
    path("checkins/<int:checkin_id>/check-out/", views.checkin_check_out, name="staff_checkin_check_out"),
    path("birthdays/", views.birthdays_anniversaries, name="staff_birthdays"),
    path("attendance/absentees/", views.absentee_list, name="staff_absentee_list"),
    path(
        "giving/lapsed-recurring-givers/",
        views.lapsed_recurring_givers_list,
        name="staff_lapsed_recurring_givers_list",
    ),
    path("followups/", views.followup_list, name="staff_followup_list"),
    path("followups/<int:follow_up_id>/", views.followup_detail, name="staff_followup_detail"),
    path("followups/<int:follow_up_id>/update-stage/", views.followup_update_stage, name="staff_followup_update_stage"),
    path("followups/<int:follow_up_id>/log-contact/", views.followup_log_contact, name="staff_followup_log_contact"),
    path("members/<int:member_id>/start-follow-up/", views.followup_start, name="staff_followup_start"),
    path("visitor-info/", views.visitor_info_edit, name="staff_visitor_info_edit"),
    path("decisions/", views.decision_list, name="staff_decision_list"),
    path("decisions/new/", views.decision_create, name="staff_decision_create"),
    path("decisions/<int:decision_id>/edit/", views.decision_edit, name="staff_decision_edit"),
    path("announcements/", views.announcement_list, name="staff_announcement_list"),
    path("announcements/new/", views.announcement_create, name="staff_announcement_create"),
    path("announcements/<int:announcement_id>/", views.announcement_detail, name="staff_announcement_detail"),
    path("announcements/<int:announcement_id>/edit/", views.announcement_edit, name="staff_announcement_edit"),
    path("announcements/<int:announcement_id>/send/", views.announcement_send, name="staff_announcement_send"),
    path(
        "announcements/<int:announcement_id>/delivery/",
        views.announcement_delivery_report,
        name="staff_announcement_delivery_report",
    ),
    path("resources/", views.resource_list, name="staff_resource_list"),
    path("resources/new/", views.resource_create, name="staff_resource_create"),
    path("resources/<int:resource_id>/edit/", views.resource_edit, name="staff_resource_edit"),
    path("bookings/", views.booking_list, name="staff_booking_list"),
    path("bookings/calendar/", views.booking_calendar, name="staff_booking_calendar"),
    path("bookings/new/", views.booking_create, name="staff_booking_create"),
    path("bookings/<int:booking_id>/edit/", views.booking_edit, name="staff_booking_edit"),
    path("care-requests/", views.care_request_list, name="staff_care_request_list"),
    path("care-requests/<int:care_request_id>/", views.care_request_detail, name="staff_care_request_detail"),
    path("surveys/", views.survey_list, name="staff_survey_list"),
    path("surveys/new/", views.survey_create, name="staff_survey_create"),
    path("surveys/<int:survey_id>/", views.survey_detail, name="staff_survey_detail"),
    path("surveys/<int:survey_id>/edit/", views.survey_edit, name="staff_survey_edit"),
    path("surveys/<int:survey_id>/questions/new/", views.survey_question_add, name="staff_survey_question_add"),
    path(
        "surveys/<int:survey_id>/questions/<int:question_id>/choices/new/",
        views.survey_choice_add,
        name="staff_survey_choice_add",
    ),
    path("dedications/", views.dedication_list, name="staff_dedication_list"),
    path("dedications/new/", views.dedication_create, name="staff_dedication_create"),
    path("dedications/<int:dedication_id>/edit/", views.dedication_edit, name="staff_dedication_edit"),
    path(
        "dedications/<int:dedication_id>/certificate/",
        views.dedication_certificate,
        name="staff_dedication_certificate",
    ),
    path("weddings/", views.wedding_list, name="staff_wedding_list"),
    path("weddings/new/", views.wedding_create, name="staff_wedding_create"),
    path("weddings/<int:wedding_id>/edit/", views.wedding_edit, name="staff_wedding_edit"),
    path("weddings/<int:wedding_id>/certificate/", views.wedding_certificate, name="staff_wedding_certificate"),
    path("baptisms/", views.baptism_list, name="staff_baptism_list"),
    path("baptisms/new/", views.baptism_create, name="staff_baptism_create"),
    path("baptisms/<int:baptism_id>/edit/", views.baptism_edit, name="staff_baptism_edit"),
    path("baptisms/<int:baptism_id>/certificate/", views.baptism_certificate, name="staff_baptism_certificate"),
    path("funerals/", views.funeral_list, name="staff_funeral_list"),
    path("funerals/new/", views.funeral_create, name="staff_funeral_create"),
    path("funerals/<int:funeral_id>/edit/", views.funeral_edit, name="staff_funeral_edit"),
    path("funerals/<int:funeral_id>/program/", views.funeral_program, name="staff_funeral_program"),
    path("transfer-letters/", views.transfer_letter_list, name="staff_transfer_letter_list"),
    path("transfer-letters/new/", views.transfer_letter_create, name="staff_transfer_letter_create"),
    path(
        "transfer-letters/<int:transfer_letter_id>/edit/",
        views.transfer_letter_edit,
        name="staff_transfer_letter_edit",
    ),
    path(
        "transfer-letters/<int:transfer_letter_id>/view/",
        views.transfer_letter_view,
        name="staff_transfer_letter_view",
    ),
    path("background-checks/", views.background_check_list, name="staff_background_check_list"),
    path("background-checks/new/", views.background_check_create, name="staff_background_check_create"),
    path(
        "background-checks/<int:background_check_id>/edit/",
        views.background_check_edit,
        name="staff_background_check_edit",
    ),
    path("trainings/", views.training_list, name="staff_training_list"),
    path("trainings/new/", views.training_create, name="staff_training_create"),
    path("trainings/<int:training_id>/edit/", views.training_edit, name="staff_training_edit"),
    path("maintenance/", views.maintenance_list, name="staff_maintenance_list"),
    path("maintenance/new/", views.maintenance_create, name="staff_maintenance_create"),
    path(
        "maintenance/<int:maintenance_request_id>/update-status/",
        views.maintenance_update_status,
        name="staff_maintenance_update_status",
    ),
    path("equipment/", views.equipment_list, name="staff_equipment_list"),
    path("equipment/new/", views.equipment_create, name="staff_equipment_create"),
    path("equipment/<int:item_id>/", views.equipment_detail, name="staff_equipment_detail"),
    path("equipment/<int:item_id>/edit/", views.equipment_edit, name="staff_equipment_edit"),
    path("equipment/<int:item_id>/checkout/", views.equipment_checkout, name="staff_equipment_checkout"),
    path("equipment/checkouts/<int:checkout_id>/checkin/", views.equipment_checkin, name="staff_equipment_checkin"),
    path("library/", views.library_list, name="staff_library_list"),
    path("library/new/", views.library_item_create, name="staff_library_item_create"),
    path("library/<int:item_id>/", views.library_item_detail, name="staff_library_item_detail"),
    path("library/<int:item_id>/edit/", views.library_item_edit, name="staff_library_item_edit"),
    path("library/<int:item_id>/checkout/", views.library_checkout, name="staff_library_checkout"),
    path("library/loans/<int:loan_id>/return/", views.library_return, name="staff_library_return"),
    path("sunday-school/", views.sunday_school_class_list, name="staff_sunday_school_class_list"),
    path("sunday-school/new/", views.sunday_school_class_create, name="staff_sunday_school_class_create"),
    path(
        "sunday-school/<int:class_id>/",
        views.sunday_school_class_detail,
        name="staff_sunday_school_class_detail",
    ),
    path(
        "sunday-school/<int:class_id>/edit/",
        views.sunday_school_class_edit,
        name="staff_sunday_school_class_edit",
    ),
    path(
        "sunday-school/<int:class_id>/children/add/",
        views.sunday_school_class_add_child,
        name="staff_sunday_school_class_add_child",
    ),
    path(
        "sunday-school/<int:class_id>/children/<int:child_id>/remove/",
        views.sunday_school_class_remove_child,
        name="staff_sunday_school_class_remove_child",
    ),
    path("service-hours/", views.service_hour_report, name="staff_service_hour_report"),
    path("service-hours/new/", views.service_hour_create, name="staff_service_hour_create"),
    path("service-hours/<int:log_id>/edit/", views.service_hour_edit, name="staff_service_hour_edit"),
    path(
        "service-hours/certificate/<int:member_id>/<int:year>/",
        views.service_hour_certificate_pdf,
        name="staff_service_hour_certificate_pdf",
    ),
    path("expenses/", views.expense_report, name="staff_expense_report"),
    path("expenses/new/", views.expense_create, name="staff_expense_create"),
    path("expenses/<int:expense_id>/edit/", views.expense_edit, name="staff_expense_edit"),
    path("budget-categories/", views.budget_category_list, name="staff_budget_category_list"),
    path("budget-categories/new/", views.budget_category_create, name="staff_budget_category_create"),
    path(
        "budget-categories/<int:category_id>/edit/",
        views.budget_category_edit,
        name="staff_budget_category_edit",
    ),
    path("meetings/", views.meeting_list, name="staff_meeting_list"),
    path("meetings/new/", views.meeting_create, name="staff_meeting_create"),
    path("meetings/<int:meeting_id>/", views.meeting_detail, name="staff_meeting_detail"),
    path("meetings/<int:meeting_id>/edit/", views.meeting_edit, name="staff_meeting_edit"),
    path(
        "meetings/<int:meeting_id>/action-items/new/",
        views.action_item_create,
        name="staff_action_item_create",
    ),
    path(
        "meetings/<int:meeting_id>/action-items/<int:item_id>/toggle/",
        views.action_item_toggle,
        name="staff_action_item_toggle",
    ),
]
