# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='Also show this on the public prayer wall, not just to staff.')),
                ('share_name_publicly', models.BooleanField(default=False, help_text='Show your name on the public wall (only matters if this request is public).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prayed_for', models.BooleanField(default=False)),
                ('prayed_for_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_pastor', models.ForeignKey(blank=True, help_text='Which pastor is following up on this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
