# Generated by Django 5.2.17 on 2026-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Main Sanctuary', 'Church Van', 'Projector #2'.", max_length=150)),
                ('resource_type', models.CharField(choices=[('room', 'Room'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment')], default='room', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Capacity, location, anything staff should know before booking.')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off once a resource is no longer available, rather than deleting it.')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="What this booking is for, e.g. 'Youth Ministry meeting'.", max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
