# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('events', '0003_eventregistration_eventservicetime_eventticket'),
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Which campus this resource belongs to (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='members.campus'),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_bookings', to='members.member'),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Link this booking to an existing event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_bookings', to='events.event'),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.resource'),
        ),
    ]
