# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(help_text='The child being dedicated.', max_length=150)),
                ('dedication_date', models.DateField()),
                ('officiated_by', models.CharField(blank=True, help_text='Which pastor/minister officiated.', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this dedication took place at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_dedications', to='members.campus')),
                ('parents', models.ManyToManyField(blank=True, help_text='Parent(s) who are members here.', related_name='baby_dedications', to='members.member')),
            ],
            options={
                'ordering': ['-dedication_date'],
            },
        ),
        migrations.CreateModel(
            name='WeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_date', models.DateField()),
                ('officiated_by', models.CharField(blank=True, help_text='Which pastor/minister officiated.', max_length=150)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this wedding took place at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_records', to='members.campus')),
                ('spouse_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings_as_spouse_one', to='members.member')),
                ('spouse_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddings_as_spouse_two', to='members.member')),
            ],
            options={
                'ordering': ['-wedding_date'],
            },
        ),
    ]
