# Generated by Django 5.2.17 on 2026-09-26 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('officiated_by', models.CharField(blank=True, help_text='Which pastor/minister officiated.', max_length=150)),
                ('location', models.CharField(blank=True, help_text='Funeral home, church, or burial site.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this service took place at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funeral_records', to='members.campus')),
                ('family_contacts', models.ManyToManyField(blank=True, help_text='Surviving family members who are also members here.', related_name='funerals_as_family_contact', to='members.member')),
                ('member', models.OneToOneField(help_text='The member who passed away.', on_delete=django.db.models.deletion.CASCADE, related_name='funeral_record', to='members.member')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
    ]
