# Generated by Django 5.2.17 on 2026-09-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
        ('milestones', '0002_funeralrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism_date', models.DateField()),
                ('officiated_by', models.CharField(blank=True, help_text='Which pastor/minister officiated.', max_length=150)),
                ('location', models.CharField(blank=True, help_text='e.g. the church baptistry, a river, or the beach.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(blank=True, help_text="Which campus this baptism took place at (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baptism_records', to='members.campus')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptism_records', to='members.member')),
            ],
            options={
                'ordering': ['-baptism_date'],
            },
        ),
    ]
