# Generated by Django 5.2.17 on 2026-09-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
        ('milestones', '0003_baptismrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_church', models.CharField(help_text='The church the member is transferring to.', max_length=200)),
                ('destination_location', models.CharField(blank=True, help_text='City/town of the destination church, if known.', max_length=200)),
                ('transfer_date', models.DateField()),
                ('issued_by', models.CharField(blank=True, help_text='Which pastor/minister issued this letter.', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_letters', to='members.member')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
    ]
