# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_times', models.TextField(blank=True, help_text='e.g. Sundays at 9:00 AM and 11:00 AM')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('wifi_network', models.CharField(blank=True, max_length=100)),
                ('wifi_password', models.CharField(blank=True, max_length=100)),
                ('what_to_expect', models.TextField(blank=True, help_text='A short welcome note - parking, dress code, what happens with kids, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Visitor info',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New Visitor'), ('contacted', 'Contacted'), ('invited', 'Invited to a Group'), ('joined', 'Became a Member'), ('inactive', 'No Longer Following Up')], default='new', max_length=10)),
                ('first_visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, help_text='General notes about this person - for a dated log of contact attempts, see below.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Which staff member is responsible for following up with this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='members.member')),
            ],
            options={
                'ordering': ['stage', '-first_visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='followup.followup')),
            ],
            options={
                'ordering': ['-contacted_at'],
            },
        ),
    ]
