# Generated by Django 5.2.17 on 2026-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='welcome_video_url',
            field=models.URLField(blank=True, help_text='A YouTube video or playlist link, embedded on the homepage whenever no live stream is currently featured there. Leave blank to show nothing in that case.'),
        ),
    ]
