# Generated by Django 5.2.17 on 2026-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='The full message, sent by email.')),
                ('sms_body', models.CharField(blank=True, help_text='Shorter version for SMS - leave blank to send the email body instead, trimmed to fit a single text.', max_length=300)),
                ('audience', models.CharField(choices=[('all', 'All Active Members'), ('campus', 'One Campus'), ('group', 'One Group')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('sms_sent_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
