# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All Active Members'), ('campus', 'One Campus'), ('group', 'One Group'), ('absentees', 'Absentee Members'), ('lapsed_givers', 'Lapsed Recurring Givers')], default='all', max_length=15),
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped_opted_out', 'Skipped (opted out)'), ('skipped_no_contact', 'Skipped (no contact info)')], max_length=20)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='announcements.announcement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_deliveries', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Announcement deliveries',
                'ordering': ['member__last_name', 'member__first_name', 'channel'],
                'unique_together': {('announcement', 'member', 'channel')},
            },
        ),
    ]
