# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('equipment', '0002_initial'),
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="Where the issue is, e.g. 'Main Sanctuary, back row'.", max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(blank=True, help_text='Link to a specific tracked equipment item, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='equipment.equipment')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='members.member')),
                ('resource', models.ForeignKey(blank=True, help_text='Link to a specific room/vehicle, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='booking.resource')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
