# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('allergies_or_medical_notes', models.TextField(blank=True, help_text="Shown to children's ministry staff at check-in - allergies, medical conditions, anything they need to know.")),
                ('is_active', models.BooleanField(default=True, help_text='Turn off once a child has aged out or the family has left, rather than deleting them.')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.household')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(help_text="Whoever dropped this child off - in case it's not a parent already on file.", max_length=150)),
                ('pickup_code', models.CharField(editable=False, max_length=6)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_check_ins_recorded', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_check_outs_recorded', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Which service/event this check-in was for, if it was tied to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_check_ins', to='events.event')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='checkin.child')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Toddlers", "Ages 5-7"', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('children', models.ManyToManyField(blank=True, related_name='sunday_school_classes', to='checkin.child')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sunday_school_classes', to='members.member')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('week_of', models.DateField(help_text='Which week this lesson is for.')),
                ('scripture_reference', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Lesson plan/curriculum notes for teachers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
                ('sunday_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='checkin.sundayschoolclass')),
            ],
            options={
                'ordering': ['-week_of'],
            },
        ),
    ]
