# Generated by Django 5.2.17 on 2026-09-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_text', models.TextField()),
                ('share_name_publicly', models.BooleanField(default=False, help_text='Show your name alongside this testimony on the public wall.')),
                ('is_approved', models.BooleanField(default=False, help_text='A Pastor has reviewed this and approved it for the public Testimony Wall.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
