# Generated by Django 5.2.17 on 2026-10-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_eventregistration_amount_due_and_more'),
        ('members', '0005_staffloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('role', models.CharField(help_text='What you served as, e.g. "Usher", "Sound tech".', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Which event this was for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_hour_logs', to='events.event')),
                ('group', models.ForeignKey(blank=True, help_text='Which ministry/team this was for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_hour_logs', to='members.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_hour_logs', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
