# Generated by Django 5.2.17 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_eventservicetime_eventticket'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Tema Main' or 'Spintex Branch'", max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('service_times', models.CharField(blank=True, help_text="e.g. 'Sundays 8:00am & 10:30am'", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['-joined_date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The small group/ministry this attendance was taken for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='members.group'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='events.eventservicetime'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_location',
            field=models.CharField(blank=True, default='', help_text="Where this group typically meets, e.g. a room or a member's home.", max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_time',
            field=models.TimeField(blank=True, help_text='When this group typically meets.', null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='left_date',
            field=models.DateField(blank=True, help_text='Left blank while the member is still active in this group.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='anniversary_date',
            field=models.DateField(blank=True, help_text='Wedding anniversary, if applicable - used for the same dashboard.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used for the staff birthdays dashboard.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_anniversary_greeting_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_birthday_greeting_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, help_text='A profile photo, shown on the dashboard and in the staff area.', null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='member',
            name='share_email_in_directory',
            field=models.BooleanField(default=False, help_text='Also show my email address to other members in the directory.'),
        ),
        migrations.AddField(
            model_name='member',
            name='share_in_directory',
            field=models.BooleanField(default=False, help_text='Show me in the member directory other logged-in members can browse.'),
        ),
        migrations.AddField(
            model_name='member',
            name='share_phone_in_directory',
            field=models.BooleanField(default=False, help_text='Also show my phone number to other members in the directory.'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date', 'event', 'group')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Which campus this attendance record was taken at, if tracked by campus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='members.campus'),
        ),
        migrations.AddField(
            model_name='member',
            name='campus',
            field=models.ForeignKey(blank=True, help_text="Which branch/campus this member belongs to (only relevant once there's more than one).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.campus'),
        ),
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('week_of', models.DateField(help_text='Which week this lesson is for.')),
                ('content', models.TextField(help_text='Lesson notes and/or discussion questions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='members.group')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
            options={
                'ordering': ['-week_of'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='interest_skills',
            field=models.ManyToManyField(blank=True, help_text="Skills/interests this group is looking for - used to suggest it to a member who's listed a matching one.", related_name='interested_groups', to='members.skill'),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills or spiritual gifts (e.g. music, hospitality, teaching) - lets staff find a volunteer for a specific need.', related_name='members', to='members.skill'),
        ),
        migrations.CreateModel(
            name='TeamShoutout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Keep it short - this goes out by email/SMS to the whole team.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoutouts', to='members.group')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. "Vocals", "Sound", "Usher".', max_length=100)),
                ('date', models.DateField(help_text='Which service date this assignment is for.')),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_assignments', to='members.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_assignments', to='members.member')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('group', 'member', 'role', 'date')},
            },
        ),
    ]
