# Generated by Django 5.2.17 on 2026-09-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_campus_skill_alter_groupmembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap on active members. Leave blank for no limit.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='calendar_token',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_by_email',
            field=models.BooleanField(default=True, help_text='Email me church-wide announcements.'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_by_sms',
            field=models.BooleanField(default=True, help_text='Text me church-wide announcements.'),
        ),
        migrations.AddField(
            model_name='servingassignment',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='Which staff member wrote this note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
