# Generated by Django 5.2.17 on 2026-09-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_group_max_members_member_calendar_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notify_giving_receipts',
            field=models.BooleanField(default=True, help_text='Email me a receipt whenever a gift of mine is recorded as completed.'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_pledge_reminders',
            field=models.BooleanField(default=True, help_text="Remind me by email/text about an outstanding pledge or a recurring gift that's due."),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_prayer_updates',
            field=models.BooleanField(default=True, help_text='Email/text me when the pastoral team has prayed for a request I submitted.'),
        ),
        migrations.AddField(
            model_name='member',
            name='notify_volunteer_reminders',
            field=models.BooleanField(default=True, help_text="Remind me by email/text the day before I'm scheduled to volunteer."),
        ),
        migrations.CreateModel(
            name='SongSetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Which service date this set list is for.')),
                ('notes', models.TextField(blank=True, help_text='Notes for the team - theme, transitions, anything else.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set_lists', to='members.group')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SetListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('key', models.CharField(blank=True, help_text='Musical key, e.g. "G", "D".', max_length=10)),
                ('ccli_number', models.CharField(blank=True, help_text='CCLI song number, if known.', max_length=20)),
                ('set_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='members.songsetlist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
